import type { DemoProduct } from "./types";

/**
 * Demo equipment catalogue.
 *
 * This is illustrative product data modeled on real, well-known gear so the
 * catalogue and product pages can be built and tested against something
 * realistic. It is NOT confirmed OUTTA inventory — availability, pricing
 * and specs here are placeholders until real inventory data replaces this
 * file.
 */
export const products: DemoProduct[] = [
  // ---------------------------------------------------------------- Cameras
  {
    id: "prod-sony-fx3",
    slug: "sony-fx3",
    sku: "OUTTA-CAM-0101",
    name: "Sony FX3",
    brandSlug: "sony",
    categorySlug: "cameras",
    tags: ["full-frame", "cinema camera", "compact", "4k", "e-mount"],
    shortDescription: "Compact full-frame cinema camera built for handheld work.",
    description:
      "A compact, full-frame cinema camera body with in-body stabilization and a fan-cooled body for extended recording. Popular for run-and-gun and gimbal work.",
    dayRate: 145,
    weekRate: 725,
    currency: "USD",
    availability: "available",
    featured: true,
    specifications: [
      { label: "Sensor", value: "Full-Frame 12.1MP Back-Illuminated CMOS", group: "Imaging" },
      { label: "Max Resolution", value: "4K UHD up to 120fps", group: "Imaging" },
      { label: "Mount", value: "Sony E-Mount", group: "Body" },
      { label: "ISO Range", value: "80–102,400 (extended)", group: "Imaging" },
      { label: "Stabilization", value: "5-axis in-body", group: "Body" },
      { label: "Weight", value: "715 g (body only)", group: "Body" },
    ],
    included: [
      "Camera body",
      "2× NP-FZ100 batteries",
      "Battery charger",
      "Top handle",
      "Camera cage",
    ],
    accessorySlugs: ["v-mount-battery-kit", "cfexpress-media-kit", "nd-filter-matte-box-kit"],
    compatibleSlugs: ["sony-24-70mm-gm-ii", "sony-70-200mm-gm-ii", "smallhd-702-touch"],
  },
  {
    id: "prod-sony-fx6",
    slug: "sony-fx6",
    sku: "OUTTA-CAM-0102",
    name: "Sony FX6",
    brandSlug: "sony",
    categorySlug: "cameras",
    tags: ["full-frame", "cinema camera", "4k", "e-mount", "documentary"],
    shortDescription: "Full-frame cinema camera with built-in ND and XLR audio.",
    description:
      "A documentary and narrative-friendly cinema camera with electronic variable ND, dual native ISO, and built-in XLR inputs — fewer accessories needed on a fast-moving set.",
    dayRate: 220,
    weekRate: 1100,
    currency: "USD",
    availability: "available",
    featured: true,
    specifications: [
      { label: "Sensor", value: "Full-Frame 10.2MP Back-Illuminated CMOS", group: "Imaging" },
      { label: "Max Resolution", value: "4K UHD up to 120fps", group: "Imaging" },
      { label: "Mount", value: "Sony E-Mount", group: "Body" },
      { label: "ND Filter", value: "Built-in electronic variable ND", group: "Body" },
      { label: "Audio", value: "2× XLR inputs on detachable handle", group: "Audio" },
      { label: "Weight", value: "890 g (body only)", group: "Body" },
    ],
    included: [
      "Camera body",
      "XLR handle unit",
      "2× BP-U batteries",
      "Battery charger",
      "Camera cage",
    ],
    accessorySlugs: ["v-mount-battery-kit", "cfexpress-media-kit", "sennheiser-ew-wireless-lav"],
    compatibleSlugs: ["sony-24-70mm-gm-ii", "sony-70-200mm-gm-ii", "smallhd-cine-7"],
  },
  {
    id: "prod-sony-fx9",
    slug: "sony-fx9",
    sku: "OUTTA-CAM-0103",
    name: "Sony FX9",
    brandSlug: "sony",
    categorySlug: "cameras",
    tags: ["full-frame", "cinema camera", "6k sensor", "e-mount", "broadcast"],
    shortDescription: "Full-frame flagship with a 6K sensor and shoulder-mount form factor.",
    description:
      "Sony's shoulder-mount full-frame flagship, built around a 6K sensor with 4K oversampled output. A strong fit for narrative and high-end broadcast work.",
    dayRate: 285,
    weekRate: 1425,
    currency: "USD",
    availability: "limited",
    specifications: [
      { label: "Sensor", value: "Full-Frame 6K Exmor R CMOS", group: "Imaging" },
      { label: "Max Resolution", value: "4K UHD oversampled from 6K", group: "Imaging" },
      { label: "Mount", value: "Sony E-Mount (interchangeable)", group: "Body" },
      { label: "ND Filter", value: "Built-in electronic variable ND", group: "Body" },
      { label: "Form Factor", value: "Shoulder-mount", group: "Body" },
      { label: "Weight", value: "2.75 kg (body only)", group: "Body" },
    ],
    included: [
      "Camera body",
      "Shoulder mount kit",
      "2× BP-U batteries",
      "Battery charger",
      "XLR handle unit",
    ],
    accessorySlugs: ["v-mount-battery-kit", "cfexpress-media-kit", "nd-filter-matte-box-kit"],
    compatibleSlugs: ["sony-70-200mm-gm-ii", "sigma-cine-prime-set", "smallhd-cine-7"],
  },
  {
    id: "prod-canon-c70",
    slug: "canon-c70",
    sku: "OUTTA-CAM-0104",
    name: "Canon C70",
    brandSlug: "canon",
    categorySlug: "cameras",
    tags: ["super 35", "cinema camera", "4k", "rf-mount", "compact"],
    shortDescription: "Compact Super 35 cinema camera with the Cinema RAW Light codec.",
    description:
      "A compact, RF-mount Super 35 cinema camera with dual gain output sensor technology, built around Canon's Cinema RAW Light workflow.",
    dayRate: 195,
    weekRate: 975,
    currency: "USD",
    availability: "available",
    specifications: [
      { label: "Sensor", value: "Super 35mm Dual Gain Output CMOS", group: "Imaging" },
      { label: "Max Resolution", value: "4K DCI up to 120fps", group: "Imaging" },
      { label: "Mount", value: "Canon RF-Mount", group: "Body" },
      { label: "Codec", value: "Cinema RAW Light, XF-AVC", group: "Imaging" },
      { label: "ND Filter", value: "Built-in electronic variable ND", group: "Body" },
      { label: "Weight", value: "1.1 kg (body only)", group: "Body" },
    ],
    included: ["Camera body", "2× batteries", "Battery charger", "Camera cage", "Top handle"],
    accessorySlugs: ["v-mount-battery-kit", "cfexpress-media-kit"],
    compatibleSlugs: ["sigma-cine-prime-set", "smallhd-702-touch"],
  },
  {
    id: "prod-arri-alexa-mini-lf",
    slug: "arri-alexa-mini-lf",
    sku: "OUTTA-CAM-0105",
    name: "ARRI Alexa Mini LF",
    brandSlug: "arri",
    categorySlug: "cameras",
    tags: ["large format", "cinema camera", "arri", "feature film", "pl-mount"],
    shortDescription: "Large-format cinema camera, the production standard on set.",
    description:
      "A large-format cinema camera built around ARRI's color science and highlight roll-off. A common choice for feature film and high-end commercial work.",
    dayRate: 650,
    weekRate: 3250,
    currency: "USD",
    availability: "on-request",
    featured: true,
    specifications: [
      { label: "Sensor", value: "Large Format ALEV III CMOS", group: "Imaging" },
      { label: "Max Resolution", value: "4.5K ARRIRAW / 4K ProRes", group: "Imaging" },
      { label: "Mount", value: "LPL (PL adapter included)", group: "Body" },
      { label: "Dynamic Range", value: "14+ stops", group: "Imaging" },
      { label: "Form Factor", value: "Mini body, full accessory ecosystem", group: "Body" },
      { label: "Weight", value: "2.3 kg (body only)", group: "Body" },
    ],
    included: [
      "Camera body",
      "PL mount adapter",
      "2× batteries",
      "Battery charger",
      "Media (CFast 2.0)",
    ],
    accessorySlugs: ["nd-filter-matte-box-kit", "v-mount-battery-kit"],
    compatibleSlugs: ["sigma-cine-prime-set", "smallhd-cine-7"],
  },
  {
    id: "prod-red-v-raptor",
    slug: "red-v-raptor",
    sku: "OUTTA-CAM-0106",
    name: "RED V-RAPTOR 8K VV",
    brandSlug: "red",
    categorySlug: "cameras",
    tags: ["8k", "vista vision", "cinema camera", "red", "feature film"],
    shortDescription: "8K Vista Vision cinema camera with an integrated ND and PL/RF mounts.",
    description:
      "RED's 8K Vista Vision sensor in a lightweight, integrated-ND body, built for high-end narrative and commercial work that needs maximum resolution headroom.",
    dayRate: 595,
    weekRate: 2975,
    currency: "USD",
    availability: "limited",
    specifications: [
      { label: "Sensor", value: "8K Vista Vision CMOS", group: "Imaging" },
      { label: "Max Resolution", value: "8K up to 120fps", group: "Imaging" },
      { label: "Mount", value: "RF (PL adapter available)", group: "Body" },
      { label: "ND Filter", value: "Built-in motorized ND", group: "Body" },
      { label: "Codec", value: "REDCODE RAW", group: "Imaging" },
      { label: "Weight", value: "2.1 kg (body only)", group: "Body" },
    ],
    included: ["Camera body", "2× batteries", "Battery charger", "Media module"],
    accessorySlugs: ["nd-filter-matte-box-kit", "cfexpress-media-kit"],
    compatibleSlugs: ["sigma-cine-prime-set", "sony-70-200mm-gm-ii"],
  },

  // ----------------------------------------------------------------- Lenses
  {
    id: "prod-sony-24-70mm-gm-ii",
    slug: "sony-24-70mm-gm-ii",
    sku: "OUTTA-LEN-0201",
    name: "Sony FE 24–70mm f/2.8 GM II",
    brandSlug: "sony",
    categorySlug: "lenses",
    tags: ["zoom", "e-mount", "f2.8", "standard zoom"],
    shortDescription: "Fast standard zoom, the everyday lens for E-mount bodies.",
    description:
      "A constant f/2.8 standard zoom covering the most-used focal range, with fast, near-silent autofocus suited to run-and-gun and hybrid work.",
    dayRate: 65,
    weekRate: 325,
    currency: "USD",
    availability: "available",
    specifications: [
      { label: "Focal Length", value: "24–70mm", group: "Optics" },
      { label: "Max Aperture", value: "f/2.8 (constant)", group: "Optics" },
      { label: "Mount", value: "Sony E-Mount", group: "Body" },
      { label: "Filter Thread", value: "82mm", group: "Body" },
      { label: "Weight", value: "695 g", group: "Body" },
    ],
    included: ["Lens", "Front and rear caps", "Lens hood", "Padded pouch"],
    accessorySlugs: ["nd-filter-matte-box-kit"],
    compatibleSlugs: ["sony-fx3", "sony-fx6", "sony-fx9"],
  },
  {
    id: "prod-sony-70-200mm-gm-ii",
    slug: "sony-70-200mm-gm-ii",
    sku: "OUTTA-LEN-0202",
    name: "Sony FE 70–200mm f/2.8 GM II",
    brandSlug: "sony",
    categorySlug: "lenses",
    tags: ["zoom", "e-mount", "f2.8", "telephoto"],
    shortDescription: "Fast telephoto zoom for interviews, sports and coverage work.",
    description:
      "A constant f/2.8 telephoto zoom with compact, lightweight construction — a common second lens for coverage, interviews and events.",
    dayRate: 70,
    weekRate: 350,
    currency: "USD",
    availability: "available",
    specifications: [
      { label: "Focal Length", value: "70–200mm", group: "Optics" },
      { label: "Max Aperture", value: "f/2.8 (constant)", group: "Optics" },
      { label: "Mount", value: "Sony E-Mount", group: "Body" },
      { label: "Filter Thread", value: "77mm", group: "Body" },
      { label: "Weight", value: "1.05 kg", group: "Body" },
    ],
    included: ["Lens", "Front and rear caps", "Lens hood", "Padded pouch"],
    accessorySlugs: ["nd-filter-matte-box-kit"],
    compatibleSlugs: ["sony-fx3", "sony-fx6", "sony-fx9", "red-v-raptor"],
  },
  {
    id: "prod-sigma-cine-prime-set",
    slug: "sigma-cine-prime-set",
    sku: "OUTTA-LEN-0203",
    name: "Sigma Cine Prime Five-Lens Set",
    brandSlug: "sigma",
    categorySlug: "lenses",
    tags: ["prime", "pl-mount", "cine", "matched set", "full-frame"],
    shortDescription: "Matched full-frame prime set with consistent color and geometry.",
    description:
      "A five-lens matched prime set — 25mm, 35mm, 50mm, 85mm, 135mm — with consistent T-stop, color and front diameter across the range. Built for narrative and commercial sets.",
    dayRate: 240,
    weekRate: 1200,
    currency: "USD",
    availability: "limited",
    featured: true,
    specifications: [
      { label: "Focal Lengths", value: "25 / 35 / 50 / 85 / 135mm", group: "Optics" },
      { label: "Max Aperture", value: "T2 (constant across set)", group: "Optics" },
      { label: "Mount", value: "PL / EF interchangeable", group: "Body" },
      { label: "Front Diameter", value: "95mm (matched)", group: "Body" },
      { label: "Housing", value: "All-metal cine housing", group: "Body" },
    ],
    included: ["5× lenses", "Hard case", "Lens support rings", "Front/rear caps (each)"],
    accessorySlugs: ["nd-filter-matte-box-kit"],
    compatibleSlugs: ["arri-alexa-mini-lf", "red-v-raptor", "canon-c70", "sony-fx9"],
  },

  // --------------------------------------------------------------- Lighting
  {
    id: "prod-aputure-600d",
    slug: "aputure-600d",
    sku: "OUTTA-LGT-0301",
    name: "Aputure LS 600d Pro",
    brandSlug: "aputure",
    categorySlug: "lighting",
    tags: ["led", "daylight", "key light", "600w"],
    shortDescription: "600W daylight-balanced LED, a common key light for interiors.",
    description:
      "A high-output daylight LED fixture with a Bowens mount, built for punching through diffusion or bouncing off large surfaces as a key light.",
    dayRate: 95,
    weekRate: 475,
    currency: "USD",
    availability: "available",
    featured: true,
    specifications: [
      { label: "Output", value: "600W daylight-balanced LED", group: "Light" },
      { label: "Color Temp", value: "5600K", group: "Light" },
      { label: "CRI/TLCI", value: "96 / 97", group: "Light" },
      { label: "Mount", value: "Bowens S-mount", group: "Body" },
      { label: "Control", value: "DMX, Sidus Link app, wireless remote", group: "Body" },
    ],
    included: ["Fixture head", "Ballast/PSU", "Light stand", "Reflector", "Cables"],
    accessorySlugs: ["v-mount-battery-kit"],
    compatibleSlugs: ["aputure-600x", "godox-vl300"],
  },
  {
    id: "prod-aputure-600x",
    slug: "aputure-600x",
    sku: "OUTTA-LGT-0302",
    name: "Aputure LS 600x Pro",
    brandSlug: "aputure",
    categorySlug: "lighting",
    tags: ["led", "bi-color", "key light", "600w"],
    shortDescription: "600W bi-color LED for scenes that need adjustable color temperature.",
    description:
      "The bi-color counterpart to the 600d — full CCT adjustment from warm tungsten to daylight, at the same 600W output class.",
    dayRate: 105,
    weekRate: 525,
    currency: "USD",
    availability: "available",
    specifications: [
      { label: "Output", value: "600W bi-color LED", group: "Light" },
      { label: "Color Temp", value: "2700K–6500K", group: "Light" },
      { label: "CRI/TLCI", value: "96 / 97", group: "Light" },
      { label: "Mount", value: "Bowens S-mount", group: "Body" },
      { label: "Control", value: "DMX, Sidus Link app, wireless remote", group: "Body" },
    ],
    included: ["Fixture head", "Ballast/PSU", "Light stand", "Reflector", "Cables"],
    accessorySlugs: ["v-mount-battery-kit"],
    compatibleSlugs: ["aputure-600d", "amaran-200x-s"],
  },
  {
    id: "prod-amaran-200x-s",
    slug: "amaran-200x-s",
    sku: "OUTTA-LGT-0303",
    name: "Amaran 200x S Bi-Color",
    brandSlug: "amaran",
    categorySlug: "lighting",
    tags: ["led", "bi-color", "budget-friendly", "200w"],
    shortDescription: "Compact 200W bi-color LED for fill and secondary lighting.",
    description:
      "A lightweight bi-color fixture that punches above its size class — a practical fill or backlight for two- and three-light setups.",
    dayRate: 45,
    weekRate: 225,
    currency: "USD",
    availability: "available",
    specifications: [
      { label: "Output", value: "200W bi-color LED", group: "Light" },
      { label: "Color Temp", value: "2700K–6500K", group: "Light" },
      { label: "CRI/TLCI", value: "95 / 96", group: "Light" },
      { label: "Mount", value: "Bowens S-mount", group: "Body" },
      { label: "Control", value: "Sidus Link app, onboard controls", group: "Body" },
    ],
    included: ["Fixture head", "PSU", "Light stand", "Reflector"],
    accessorySlugs: ["v-mount-battery-kit"],
    compatibleSlugs: ["aputure-600x", "godox-vl300"],
  },
  {
    id: "prod-godox-vl300",
    slug: "godox-vl300",
    sku: "OUTTA-LGT-0304",
    name: "Godox VL300",
    brandSlug: "godox",
    categorySlug: "lighting",
    tags: ["led", "daylight", "budget-friendly", "300w"],
    shortDescription: "300W daylight LED with a Bowens mount, built for value setups.",
    description:
      "A dependable daylight-balanced LED fixture at a lower price point — useful when a kit needs an extra head without stretching the lighting budget.",
    dayRate: 40,
    weekRate: 200,
    currency: "USD",
    availability: "limited",
    specifications: [
      { label: "Output", value: "300W daylight-balanced LED", group: "Light" },
      { label: "Color Temp", value: "5600K", group: "Light" },
      { label: "CRI/TLCI", value: "96 / 97", group: "Light" },
      { label: "Mount", value: "Bowens S-mount", group: "Body" },
      { label: "Control", value: "DMX, onboard controls", group: "Body" },
    ],
    included: ["Fixture head", "PSU", "Light stand", "Reflector"],
    accessorySlugs: ["v-mount-battery-kit"],
    compatibleSlugs: ["aputure-600d", "amaran-200x-s"],
  },

  // -------------------------------------------------------------------- Grip
  {
    id: "prod-sachtler-flowtech-75",
    slug: "sachtler-flowtech-75",
    sku: "OUTTA-GRP-0401",
    name: "Sachtler Flowtech 75 Tripod System",
    brandSlug: "sachtler",
    categorySlug: "grip",
    tags: ["tripod", "fluid head", "support"],
    shortDescription: "Fluid-head tripod system for smooth pan, tilt and precise framing.",
    description:
      "A carbon-fiber tripod system with a counterbalanced fluid head, built for smooth handheld-free camera moves and fast set-up between setups.",
    dayRate: 55,
    weekRate: 275,
    currency: "USD",
    availability: "available",
    specifications: [
      { label: "Head Type", value: "Fluid head, 75mm bowl", group: "Support" },
      { label: "Payload", value: "Up to 15kg", group: "Support" },
      { label: "Legs", value: "Carbon fiber, flip-lock", group: "Support" },
      { label: "Counterbalance", value: "Continuous, adjustable", group: "Support" },
      { label: "Weight", value: "5.4 kg (complete system)", group: "Support" },
    ],
    included: ["Tripod legs", "Fluid head", "Ground spreader", "Carrying case"],
    accessorySlugs: [],
    compatibleSlugs: ["sony-fx6", "sony-fx9", "canon-c70", "arri-alexa-mini-lf"],
  },
  {
    id: "prod-dji-rs-3-pro",
    slug: "dji-rs-3-pro",
    sku: "OUTTA-GRP-0402",
    name: "DJI RS 3 Pro",
    brandSlug: "dji",
    categorySlug: "grip",
    tags: ["gimbal", "stabilizer", "handheld"],
    shortDescription: "3-axis handheld gimbal stabilizer for cinema and mirrorless bodies.",
    description:
      "A 3-axis motorized stabilizer with a high payload capacity and automated axis locks — built for handheld moving shots without a Steadicam operator.",
    dayRate: 75,
    weekRate: 375,
    currency: "USD",
    availability: "available",
    featured: true,
    specifications: [
      { label: "Payload", value: "Up to 4.5kg", group: "Support" },
      { label: "Axes", value: "3-axis motorized stabilization", group: "Support" },
      { label: "Battery Life", value: "Up to 12 hours", group: "Support" },
      { label: "Monitor", value: "1.8\" full-color touchscreen", group: "Body" },
      { label: "Weight", value: "1.5 kg (gimbal only)", group: "Body" },
    ],
    included: ["Gimbal", "Battery grip", "Tripod stand", "Carrying case"],
    accessorySlugs: ["v-mount-battery-kit"],
    compatibleSlugs: ["sony-fx3", "canon-c70"],
  },
  {
    id: "prod-c-stand-kit",
    slug: "c-stand-kit",
    sku: "OUTTA-GRP-0403",
    name: "C-Stand Kit with Grip Head & Arm",
    brandSlug: "outta-essentials",
    categorySlug: "grip",
    tags: ["c-stand", "grip", "rigging"],
    shortDescription: "Standard C-stand with grip head and arm — the set workhorse.",
    description:
      "A 40\" C-stand with a turtle base, grip head and extension arm — the standard support for flags, nets, small fixtures and bounce boards on any set.",
    dayRate: 20,
    weekRate: 100,
    currency: "USD",
    availability: "available",
    specifications: [
      { label: "Height Range", value: "40\"–121\"", group: "Support" },
      { label: "Base", value: "Turtle base", group: "Support" },
      { label: "Arm", value: "20\" grip arm included", group: "Support" },
      { label: "Payload", value: "Up to 10kg (with sandbag)", group: "Support" },
    ],
    included: ["C-stand", "Grip head", "20\" arm", "Sandbag"],
    accessorySlugs: [],
    compatibleSlugs: ["aputure-600d", "aputure-600x", "amaran-200x-s"],
  },
  {
    id: "prod-camera-slider",
    slug: "camera-slider",
    sku: "OUTTA-GRP-0404",
    name: "4ft Motorized Camera Slider",
    brandSlug: "outta-essentials",
    categorySlug: "grip",
    tags: ["slider", "motorized", "dolly move"],
    shortDescription: "Motorized slider for smooth, repeatable dolly-style moves.",
    description:
      "A 4-foot motorized slider with programmable moves and adjustable speed — a compact way to add production value without a full dolly and track setup.",
    dayRate: 65,
    weekRate: 325,
    currency: "USD",
    availability: "limited",
    specifications: [
      { label: "Track Length", value: "4ft (122cm)", group: "Support" },
      { label: "Payload", value: "Up to 8kg", group: "Support" },
      { label: "Motion Control", value: "App-controlled, programmable moves", group: "Body" },
      { label: "Weight", value: "3.2 kg", group: "Body" },
    ],
    included: ["Slider rail", "Motor unit", "Carrying case", "Remote control"],
    accessorySlugs: [],
    compatibleSlugs: ["sony-fx3", "sony-fx6"],
  },

  // ------------------------------------------------------------------- Audio
  {
    id: "prod-sennheiser-ew-dx",
    slug: "sennheiser-ew-wireless-lav",
    sku: "OUTTA-AUD-0501",
    name: "Sennheiser EW-DX Wireless Lavalier Kit",
    brandSlug: "sennheiser",
    categorySlug: "audio",
    tags: ["wireless", "lavalier", "dialogue"],
    shortDescription: "Dual-channel digital wireless system with two bodypack transmitters.",
    description:
      "A digital wireless lavalier system with a dual-channel receiver and two bodypack transmitters — clean, reliable dialogue capture for interviews and narrative.",
    dayRate: 55,
    weekRate: 275,
    currency: "USD",
    availability: "available",
    featured: true,
    specifications: [
      { label: "Channels", value: "2 (dual-channel receiver)", group: "Audio" },
      { label: "Range", value: "Up to 250m line of sight", group: "Audio" },
      { label: "Transmitters", value: "2× bodypack, includes lavalier mics", group: "Audio" },
      { label: "Battery Life", value: "Up to 12 hours per transmitter", group: "Audio" },
    ],
    included: ["Receiver", "2× bodypack transmitters", "2× lavalier mics", "Cables", "Case"],
    accessorySlugs: [],
    compatibleSlugs: ["sony-fx6", "boom-pole-shotgun-kit"],
  },
  {
    id: "prod-boom-pole-shotgun-kit",
    slug: "boom-pole-shotgun-kit",
    sku: "OUTTA-AUD-0502",
    name: "Boom Pole & Shotgun Mic Kit",
    brandSlug: "outta-essentials",
    categorySlug: "audio",
    tags: ["boom", "shotgun mic", "dialogue"],
    shortDescription: "Shotgun microphone, boom pole and blimp for on-set dialogue.",
    description:
      "A matched shotgun mic, carbon-fiber boom pole and wind protection blimp — set up for a boom operator to work close to camera on dialogue-heavy scenes.",
    dayRate: 45,
    weekRate: 225,
    currency: "USD",
    availability: "available",
    specifications: [
      { label: "Microphone", value: "Shotgun, supercardioid pattern", group: "Audio" },
      { label: "Boom Pole", value: "Carbon fiber, 5-section, 3m extended", group: "Body" },
      { label: "Wind Protection", value: "Blimp with deadcat cover", group: "Body" },
      { label: "Output", value: "XLR", group: "Audio" },
    ],
    included: ["Shotgun mic", "Boom pole", "Blimp & deadcat", "XLR cable"],
    accessorySlugs: [],
    compatibleSlugs: ["sennheiser-ew-wireless-lav", "zoom-field-recorder"],
  },
  {
    id: "prod-field-recorder",
    slug: "zoom-field-recorder",
    sku: "OUTTA-AUD-0503",
    name: "8-Channel Field Audio Recorder",
    brandSlug: "outta-essentials",
    categorySlug: "audio",
    tags: ["field recorder", "multitrack", "location sound"],
    shortDescription: "8-channel multitrack recorder for location sound mixing.",
    description:
      "An 8-input, timecode-capable field recorder for productions running multiple wireless channels and a boom simultaneously.",
    dayRate: 60,
    weekRate: 300,
    currency: "USD",
    availability: "on-request",
    specifications: [
      { label: "Inputs", value: "8× XLR/TRS combo", group: "Audio" },
      { label: "Timecode", value: "Built-in generator, jam-sync", group: "Audio" },
      { label: "Recording Format", value: "Up to 32-bit float / 192kHz", group: "Audio" },
      { label: "Media", value: "Dual SD card slots", group: "Body" },
    ],
    included: ["Recorder", "Power supply", "SD cards (2×)", "Carrying case"],
    accessorySlugs: [],
    compatibleSlugs: ["sennheiser-ew-wireless-lav", "boom-pole-shotgun-kit"],
  },

  // ---------------------------------------------------------------- Monitors
  {
    id: "prod-smallhd-702-touch",
    slug: "smallhd-702-touch",
    sku: "OUTTA-MON-0601",
    name: "SmallHD 702 Touch",
    brandSlug: "smallhd",
    categorySlug: "monitors",
    tags: ["on-camera monitor", "touchscreen", "7-inch"],
    shortDescription: "7\" touchscreen on-camera monitor with waveform and false color.",
    description:
      "A 7-inch, 1000-nit on-camera monitor with a touchscreen interface, waveform, vectorscope and false-color exposure tools built in.",
    dayRate: 40,
    weekRate: 200,
    currency: "USD",
    availability: "available",
    specifications: [
      { label: "Screen Size", value: "7-inch, 1920×1200", group: "Display" },
      { label: "Brightness", value: "1000 nits", group: "Display" },
      { label: "Tools", value: "Waveform, vectorscope, false color, focus peaking", group: "Display" },
      { label: "Input", value: "3G-SDI, HDMI", group: "Body" },
    ],
    included: ["Monitor", "Mounting arm", "Sun hood", "Battery plate"],
    accessorySlugs: ["v-mount-battery-kit"],
    compatibleSlugs: ["sony-fx3", "canon-c70"],
  },
  {
    id: "prod-smallhd-cine-7",
    slug: "smallhd-cine-7",
    sku: "OUTTA-MON-0602",
    name: "SmallHD Cine 7",
    brandSlug: "smallhd",
    categorySlug: "monitors",
    tags: ["on-camera monitor", "daylight visible", "7-inch"],
    shortDescription: "Daylight-visible 7\" monitor built for high-end cinema workflows.",
    description:
      "A daylight-visible on-camera monitor built to pair with cinema camera bodies, with 3D LUT support and camera control over SDI for compatible bodies.",
    dayRate: 55,
    weekRate: 275,
    currency: "USD",
    availability: "limited",
    specifications: [
      { label: "Screen Size", value: "7-inch, 2000-nit daylight visible", group: "Display" },
      { label: "3D LUT Support", value: "Yes, loadable via USB", group: "Display" },
      { label: "Camera Control", value: "SDI control for supported bodies", group: "Body" },
      { label: "Input", value: "3G-SDI ×2, HDMI", group: "Body" },
    ],
    included: ["Monitor", "Mounting arm", "Sun hood", "Battery plate"],
    accessorySlugs: ["v-mount-battery-kit"],
    compatibleSlugs: ["arri-alexa-mini-lf", "sony-fx9", "red-v-raptor"],
  },

  // ------------------------------------------------------------------ Drones
  {
    id: "prod-dji-inspire-3",
    slug: "dji-inspire-3",
    sku: "OUTTA-DRN-0701",
    name: "DJI Inspire 3",
    brandSlug: "dji",
    categorySlug: "drones",
    tags: ["drone", "cinema", "8k", "aerial"],
    shortDescription: "Cinema-grade aerial platform with an 8K full-frame sensor.",
    description:
      "A cinema-grade aerial platform built around a full-frame 8K sensor with dual-operator control — for productions that need aerial coverage matched to ground camera color.",
    dayRate: 450,
    weekRate: 2250,
    currency: "USD",
    availability: "on-request",
    specifications: [
      { label: "Sensor", value: "Full-Frame 8K", group: "Imaging" },
      { label: "Flight Time", value: "Up to 28 minutes", group: "Flight" },
      { label: "Control", value: "Dual-operator (pilot + camera)", group: "Flight" },
      { label: "Transmission Range", value: "Up to 15km (unobstructed)", group: "Flight" },
    ],
    included: ["Aircraft", "2× controllers", "Batteries", "Charging hub", "Case"],
    accessorySlugs: ["nd-filter-matte-box-kit", "cfexpress-media-kit"],
    compatibleSlugs: ["dji-mavic-3-cine"],
  },
  {
    id: "prod-dji-mavic-3-cine",
    slug: "dji-mavic-3-cine",
    sku: "OUTTA-DRN-0702",
    name: "DJI Mavic 3 Cine",
    brandSlug: "dji",
    categorySlug: "drones",
    tags: ["drone", "compact", "4k", "aerial"],
    shortDescription: "Compact aerial platform for fast-turnaround coverage and B-roll.",
    description:
      "A compact, foldable drone with a 4/3 CMOS sensor and Apple ProRes recording — practical for productions that need quick aerial B-roll without a full aerial crew.",
    dayRate: 150,
    weekRate: 750,
    currency: "USD",
    availability: "available",
    specifications: [
      { label: "Sensor", value: "4/3 CMOS", group: "Imaging" },
      { label: "Max Resolution", value: "5.1K / 4K ProRes", group: "Imaging" },
      { label: "Flight Time", value: "Up to 46 minutes", group: "Flight" },
      { label: "Transmission Range", value: "Up to 15km (unobstructed)", group: "Flight" },
    ],
    included: ["Aircraft", "Controller", "3× batteries", "Charging hub", "Case"],
    accessorySlugs: ["cfexpress-media-kit"],
    compatibleSlugs: ["dji-inspire-3"],
  },

  // ------------------------------------------------------------- Accessories
  {
    id: "prod-v-mount-battery-kit",
    slug: "v-mount-battery-kit",
    sku: "OUTTA-ACC-0801",
    name: "V-Mount Battery & Charger Kit",
    brandSlug: "outta-essentials",
    categorySlug: "accessories",
    tags: ["battery", "power", "v-mount"],
    shortDescription: "Two V-mount batteries with a dual-position charger.",
    description:
      "A pair of high-capacity V-mount batteries with a dual charger — the standard power solution for cameras, monitors and lighting fixtures across a shoot day.",
    dayRate: 25,
    weekRate: 125,
    currency: "USD",
    availability: "available",
    specifications: [
      { label: "Capacity", value: "2× 150Wh V-mount batteries", group: "Power" },
      { label: "Charger", value: "Dual-position, fast charge", group: "Power" },
      { label: "Outputs", value: "D-tap, USB-C PD", group: "Power" },
    ],
    included: ["2× V-mount batteries", "Dual charger", "D-tap cable"],
    accessorySlugs: [],
    compatibleSlugs: ["sony-fx6", "sony-fx9", "aputure-600d", "aputure-600x"],
  },
  {
    id: "prod-nd-filter-matte-box-kit",
    slug: "nd-filter-matte-box-kit",
    sku: "OUTTA-ACC-0802",
    name: "Matte Box & ND Filter Kit",
    brandSlug: "outta-essentials",
    categorySlug: "accessories",
    tags: ["matte box", "nd filter", "filtration"],
    shortDescription: "Clamp-on matte box with a full set of graduated ND filters.",
    description:
      "A lightweight clamp-on matte box with a set of 4×5.65 ND filters (0.3 to 1.8 density) — flag off flares and control exposure without stepping down the iris.",
    dayRate: 35,
    weekRate: 175,
    currency: "USD",
    availability: "available",
    specifications: [
      { label: "Format", value: "4×5.65\" filter trays", group: "Filtration" },
      { label: "ND Set", value: "0.3 / 0.6 / 0.9 / 1.2 / 1.8 density", group: "Filtration" },
      { label: "Mounting", value: "Clamp-on, 80–114mm", group: "Body" },
    ],
    included: ["Matte box", "5× ND filters", "French flag", "Clamp adapter"],
    accessorySlugs: [],
    compatibleSlugs: ["sony-24-70mm-gm-ii", "sigma-cine-prime-set"],
  },
  {
    id: "prod-cfexpress-media-kit",
    slug: "cfexpress-media-kit",
    sku: "OUTTA-ACC-0803",
    name: "CFexpress Type B Media Kit",
    brandSlug: "outta-essentials",
    categorySlug: "accessories",
    tags: ["media", "cfexpress", "storage"],
    shortDescription: "Four CFexpress Type B cards with a high-speed card reader.",
    description:
      "Four high-endurance CFexpress Type B cards and a Thunderbolt card reader — enough media to cover a full shoot day across most cinema camera bodies.",
    dayRate: 30,
    weekRate: 150,
    currency: "USD",
    availability: "available",
    specifications: [
      { label: "Capacity", value: "4× 325GB CFexpress Type B", group: "Storage" },
      { label: "Read Speed", value: "Up to 1700MB/s", group: "Storage" },
      { label: "Reader", value: "Thunderbolt 3 card reader included", group: "Storage" },
    ],
    included: ["4× CFexpress cards", "Card reader", "Protective case"],
    accessorySlugs: [],
    compatibleSlugs: ["sony-fx3", "sony-fx6", "sony-fx9", "canon-c70", "red-v-raptor"],
  },
];
