import type { DemoProduct } from "./types";

/**
 * OUTTA's real rental catalogue — cameras, lenses, camera accessories,
 * filters, matte boxes, lighting fixtures and lighting modifiers, priced
 * from OUTTA's actual rate sheet. Audio and drones have no real inventory
 * data yet, so those categories are intentionally empty rather than filled
 * with placeholders.
 */
export const products: DemoProduct[] = [
  {
    id: "prod-sony-fx3",
    slug: "sony-fx3",
    sku: "OUTTA-CAM-0101",
    name: "Sony FX3 (Cine Style)",
    brandSlug: "sony",
    categorySlug: "cameras",
    tags: ["full-frame", "cinema camera", "compact", "4k", "e-mount"],
    shortDescription: "Compact full-frame cinema camera built for handheld work.",
    description:
      "A compact, full-frame cinema camera body with in-body stabilization and a fan-cooled body for extended recording. Popular for run-and-gun and gimbal work.",
    dayRate: 800,
    weekRate: 4000,
    currency: "GHS",
    availability: "available",
    featured: true,
    specifications: [
      { label: "Sensor", value: "Full-Frame 12.1MP Back-Illuminated CMOS", group: "Imaging" },
      { label: "Max Resolution", value: "4K UHD up to 120fps", group: "Imaging" },
      { label: "Mount", value: "Sony E-Mount", group: "Body" },
      { label: "ISO Range", value: "80–102,400 (extended)", group: "Imaging" },
      { label: "Stabilization", value: "5-axis in-body", group: "Body" },
      { label: "Weight", value: "715 g (body only)", group: "Body" },
    ],
    included: [
      "Camera body",
      "2× NP-FZ100 batteries",
      "Battery charger",
      "Top handle",
      "Camera cage",
    ],
    accessorySlugs: ["v-mount-battery-kit", "cfexpress-media-kit", "nd-filter-matte-box-kit"],
    compatibleSlugs: ["sony-24-70mm-gm-ii", "sony-70-200mm-gm-ii", "smallhd-702-touch"],
  },
  {
    id: "prod-aputure-600d",
    slug: "aputure-600d",
    sku: "OUTTA-LGT-0301",
    name: "Aputure LS 600d Pro",
    brandSlug: "aputure",
    categorySlug: "lighting",
    tags: ["led", "daylight", "key light", "600w"],
    shortDescription: "600W daylight-balanced LED, a common key light for interiors.",
    description:
      "A high-output daylight LED fixture with a Bowens mount, built for punching through diffusion or bouncing off large surfaces as a key light.",
    dayRate: 400,
    weekRate: 2000,
    currency: "GHS",
    availability: "available",
    featured: true,
    specifications: [
      { label: "Output", value: "600W daylight-balanced LED", group: "Light" },
      { label: "Color Temp", value: "5600K", group: "Light" },
      { label: "CRI/TLCI", value: "96 / 97", group: "Light" },
      { label: "Mount", value: "Bowens S-mount", group: "Body" },
      { label: "Control", value: "DMX, Sidus Link app, wireless remote", group: "Body" },
    ],
    included: ["Fixture head", "Ballast/PSU", "Light stand", "Reflector", "Cables"],
    accessorySlugs: ["v-mount-battery-kit"],
    compatibleSlugs: ["aputure-600x", "godox-vl300"],
  },
  {
    id: "prod-aputure-600x",
    slug: "aputure-600x",
    sku: "OUTTA-LGT-0302",
    name: "Aputure LS 600x Pro",
    brandSlug: "aputure",
    categorySlug: "lighting",
    tags: ["led", "bi-color", "key light", "600w"],
    shortDescription: "600W bi-color LED for scenes that need adjustable color temperature.",
    description:
      "The bi-color counterpart to the 600d — full CCT adjustment from warm tungsten to daylight, at the same 600W output class.",
    dayRate: 500,
    weekRate: 2500,
    currency: "GHS",
    availability: "available",
    specifications: [
      { label: "Output", value: "600W bi-color LED", group: "Light" },
      { label: "Color Temp", value: "2700K–6500K", group: "Light" },
      { label: "CRI/TLCI", value: "96 / 97", group: "Light" },
      { label: "Mount", value: "Bowens S-mount", group: "Body" },
      { label: "Control", value: "DMX, Sidus Link app, wireless remote", group: "Body" },
    ],
    included: ["Fixture head", "Ballast/PSU", "Light stand", "Reflector", "Cables"],
    accessorySlugs: ["v-mount-battery-kit"],
    compatibleSlugs: ["aputure-600d", "amaran-200x-s"],
  },
  {
    id: "prod-amaran-200x-s",
    slug: "amaran-200x-s",
    sku: "OUTTA-LGT-0303",
    name: "Amaran 200x S Bi-Color",
    brandSlug: "amaran",
    categorySlug: "lighting",
    tags: ["led", "bi-color", "budget-friendly", "200w"],
    shortDescription: "Compact 200W bi-color LED for fill and secondary lighting.",
    description:
      "A lightweight bi-color fixture that punches above its size class — a practical fill or backlight for two- and three-light setups.",
    dayRate: 200,
    weekRate: 1000,
    currency: "GHS",
    availability: "available",
    specifications: [
      { label: "Output", value: "200W bi-color LED", group: "Light" },
      { label: "Color Temp", value: "2700K–6500K", group: "Light" },
      { label: "CRI/TLCI", value: "95 / 96", group: "Light" },
      { label: "Mount", value: "Bowens S-mount", group: "Body" },
      { label: "Control", value: "Sidus Link app, onboard controls", group: "Body" },
    ],
    included: ["Fixture head", "PSU", "Light stand", "Reflector"],
    accessorySlugs: ["v-mount-battery-kit"],
    compatibleSlugs: ["aputure-600x", "godox-vl300"],
  },
  {
    id: "prod-c-stand-kit",
    slug: "c-stand-kit",
    sku: "OUTTA-GRP-0403",
    name: "C-Stand Kit with Grip Head & Arm",
    brandSlug: "outta-essentials",
    categorySlug: "grip",
    tags: ["c-stand", "grip", "rigging"],
    shortDescription: "Standard C-stand with grip head and arm — the set workhorse.",
    description:
      "A 40\" C-stand with a turtle base, grip head and extension arm — the standard support for flags, nets, small fixtures and bounce boards on any set.",
    dayRate: 70,
    weekRate: 350,
    currency: "GHS",
    availability: "available",
    specifications: [
      { label: "Height Range", value: "40\"–121\"", group: "Support" },
      { label: "Base", value: "Turtle base", group: "Support" },
      { label: "Arm", value: "20\" grip arm included", group: "Support" },
      { label: "Payload", value: "Up to 10kg (with sandbag)", group: "Support" },
    ],
    included: ["C-stand", "Grip head", "20\" arm", "Sandbag"],
    accessorySlugs: [],
    compatibleSlugs: ["aputure-600d", "aputure-600x", "amaran-200x-s"],
  },
  {
    id: "prod-arri-alexa-mini",
    slug: "arri-alexa-mini",
    sku: "OUTTA-CAM-0107",
    name: "ARRI Alexa Mini",
    brandSlug: "arri",
    categorySlug: "cameras",
    tags: ["cameras"],
    shortDescription: "Real OUTTA inventory — camera body, available to rent.",
    description: "ARRI Alexa Mini — camera body from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 3500,
    weekRate: 17500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-arri-alexa-mini-foreign",
    slug: "arri-alexa-mini-foreign",
    sku: "OUTTA-CAM-0108",
    name: "ARRI Alexa Mini (Foreign)",
    brandSlug: "arri",
    categorySlug: "cameras",
    tags: ["cameras"],
    shortDescription: "Real OUTTA inventory — camera body, available to rent.",
    description: "ARRI Alexa Mini (Foreign) — camera body from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 350,
    weekRate: 1750,
    currency: "USD",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-red-helium",
    slug: "red-helium",
    sku: "OUTTA-CAM-0109",
    name: "RED Helium",
    brandSlug: "red",
    categorySlug: "cameras",
    tags: ["cameras"],
    shortDescription: "Real OUTTA inventory — camera body, available to rent.",
    description: "RED Helium — camera body from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 2000,
    weekRate: 10000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-blackmagic-6k-pro",
    slug: "blackmagic-6k-pro",
    sku: "OUTTA-CAM-0110",
    name: "Blackmagic 6K Pro",
    brandSlug: "blackmagic",
    categorySlug: "cameras",
    tags: ["cameras"],
    shortDescription: "Real OUTTA inventory — camera body, available to rent.",
    description: "Blackmagic 6K Pro — camera body from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 500,
    weekRate: 2500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-blackmagic-6k",
    slug: "blackmagic-6k",
    sku: "OUTTA-CAM-0111",
    name: "Blackmagic 6K",
    brandSlug: "blackmagic",
    categorySlug: "cameras",
    tags: ["cameras"],
    shortDescription: "Real OUTTA inventory — camera body, available to rent.",
    description: "Blackmagic 6K — camera body from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 500,
    weekRate: 2500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-dzofilm-arles-prime-set-25-35-50-75-100mm",
    slug: "dzofilm-arles-prime-set-25-35-50-75-100mm",
    sku: "OUTTA-LEN-0204",
    name: "DZOFilm Arles Prime Set (25/35/50/75/100mm)",
    brandSlug: "dzofilm",
    categorySlug: "lenses",
    tags: ["lenses"],
    shortDescription: "Real OUTTA inventory — cine prime lens set, available to rent.",
    description: "DZOFilm Arles Prime Set (25/35/50/75/100mm) — cine prime lens set from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 4500,
    weekRate: 22500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-dzofilm-arles-prime-single",
    slug: "dzofilm-arles-prime-single",
    sku: "OUTTA-LEN-0205",
    name: "DZOFilm Arles Prime (Single)",
    brandSlug: "dzofilm",
    categorySlug: "lenses",
    tags: ["lenses"],
    shortDescription: "Real OUTTA inventory — cine prime lens, available to rent.",
    description: "DZOFilm Arles Prime (Single) — cine prime lens from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 1000,
    weekRate: 5000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-dzofilm-vespid-prime-set-16-125mm",
    slug: "dzofilm-vespid-prime-set-16-125mm",
    sku: "OUTTA-LEN-0206",
    name: "DZOFilm Vespid Prime Set (16-125mm)",
    brandSlug: "dzofilm",
    categorySlug: "lenses",
    tags: ["lenses"],
    shortDescription: "Real OUTTA inventory — cine prime lens set, available to rent.",
    description: "DZOFilm Vespid Prime Set (16-125mm) — cine prime lens set from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 3500,
    weekRate: 17500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-dzofilm-pictor-zoom-12-25mm-t2-8",
    slug: "dzofilm-pictor-zoom-12-25mm-t2-8",
    sku: "OUTTA-LEN-0207",
    name: "DZOFilm Pictor Zoom 12-25mm T2.8",
    brandSlug: "dzofilm",
    categorySlug: "lenses",
    tags: ["lenses"],
    shortDescription: "Real OUTTA inventory — cine zoom lens, available to rent.",
    description: "DZOFilm Pictor Zoom 12-25mm T2.8 — cine zoom lens from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 700,
    weekRate: 3500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-dzofilm-pictor-zoom-20-55mm-t2-8",
    slug: "dzofilm-pictor-zoom-20-55mm-t2-8",
    sku: "OUTTA-LEN-0208",
    name: "DZOFilm Pictor Zoom 20-55mm T2.8",
    brandSlug: "dzofilm",
    categorySlug: "lenses",
    tags: ["lenses"],
    shortDescription: "Real OUTTA inventory — cine zoom lens, available to rent.",
    description: "DZOFilm Pictor Zoom 20-55mm T2.8 — cine zoom lens from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 600,
    weekRate: 3000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-dzofilm-pictor-zoom-50-125mm-t2-8",
    slug: "dzofilm-pictor-zoom-50-125mm-t2-8",
    sku: "OUTTA-LEN-0209",
    name: "DZOFilm Pictor Zoom 50-125mm T2.8",
    brandSlug: "dzofilm",
    categorySlug: "lenses",
    tags: ["lenses"],
    shortDescription: "Real OUTTA inventory — cine zoom lens, available to rent.",
    description: "DZOFilm Pictor Zoom 50-125mm T2.8 — cine zoom lens from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 600,
    weekRate: 3000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-arri-distagon-12mm",
    slug: "arri-distagon-12mm",
    sku: "OUTTA-LEN-0210",
    name: "ARRI Distagon 12mm",
    brandSlug: "arri",
    categorySlug: "lenses",
    tags: ["lenses"],
    shortDescription: "Real OUTTA inventory — cine prime lens, available to rent.",
    description: "ARRI Distagon 12mm — cine prime lens from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 1000,
    weekRate: 5000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-laowa-12mm-ef",
    slug: "laowa-12mm-ef",
    sku: "OUTTA-LEN-0211",
    name: "Laowa 12mm EF",
    brandSlug: "laowa",
    categorySlug: "lenses",
    tags: ["lenses"],
    shortDescription: "Real OUTTA inventory — cine lens, available to rent.",
    description: "Laowa 12mm EF — cine lens from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 500,
    weekRate: 2500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-sigma-18-35mm",
    slug: "sigma-18-35mm",
    sku: "OUTTA-LEN-0212",
    name: "Sigma 18-35mm",
    brandSlug: "sigma",
    categorySlug: "lenses",
    tags: ["lenses"],
    shortDescription: "Real OUTTA inventory — zoom lens, available to rent.",
    description: "Sigma 18-35mm — zoom lens from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 150,
    weekRate: 750,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-canon-24-105mm",
    slug: "canon-24-105mm",
    sku: "OUTTA-LEN-0213",
    name: "Canon 24-105mm",
    brandSlug: "canon",
    categorySlug: "lenses",
    tags: ["lenses"],
    shortDescription: "Real OUTTA inventory — zoom lens, available to rent.",
    description: "Canon 24-105mm — zoom lens from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 120,
    weekRate: 600,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-heavy-duty-tripod",
    slug: "heavy-duty-tripod",
    sku: "OUTTA-CAC-0901",
    name: "Heavy Duty Tripod",
    brandSlug: "outta-essentials",
    categorySlug: "camera-accessories",
    tags: ["camera-accessories"],
    shortDescription: "Real OUTTA inventory — camera support, available to rent.",
    description: "Heavy Duty Tripod — camera support from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 600,
    weekRate: 3000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-wireless-focus-system",
    slug: "wireless-focus-system",
    sku: "OUTTA-CAC-0902",
    name: "Wireless Focus System",
    brandSlug: "tilta",
    categorySlug: "camera-accessories",
    tags: ["camera-accessories"],
    shortDescription: "Real OUTTA inventory — wireless follow focus system, available to rent.",
    description: "Wireless Focus System — wireless follow focus system from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 1500,
    weekRate: 7500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-lidar-focus-pro",
    slug: "lidar-focus-pro",
    sku: "OUTTA-CAC-0903",
    name: "Lidar Focus Pro",
    brandSlug: "tilta",
    categorySlug: "camera-accessories",
    tags: ["camera-accessories"],
    shortDescription: "Real OUTTA inventory — lidar autofocus system, available to rent.",
    description: "Lidar Focus Pro — lidar autofocus system from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 1500,
    weekRate: 7500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-teradek-wireless-video-transmitter",
    slug: "teradek-wireless-video-transmitter",
    sku: "OUTTA-CAC-0904",
    name: "Teradek Wireless Video Transmitter",
    brandSlug: "teradek",
    categorySlug: "camera-accessories",
    tags: ["camera-accessories"],
    shortDescription: "Real OUTTA inventory — wireless video transmitter, available to rent.",
    description: "Teradek Wireless Video Transmitter — wireless video transmitter from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 1200,
    weekRate: 6000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-smallhd-dir-monitor",
    slug: "smallhd-dir-monitor",
    sku: "OUTTA-CAC-0905",
    name: "SmallHD DIR Monitor",
    brandSlug: "smallhd",
    categorySlug: "camera-accessories",
    tags: ["camera-accessories"],
    shortDescription: "Real OUTTA inventory — on-camera monitor, available to rent.",
    description: "SmallHD DIR Monitor — on-camera monitor from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 1200,
    weekRate: 6000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-atomos-sumo-19-monitor",
    slug: "atomos-sumo-19-monitor",
    sku: "OUTTA-CAC-0906",
    name: "Atomos Sumo 19\" Monitor",
    brandSlug: "atomos",
    categorySlug: "camera-accessories",
    tags: ["camera-accessories"],
    shortDescription: "Real OUTTA inventory — production monitor/recorder, available to rent.",
    description: "Atomos Sumo 19\" Monitor — production monitor/recorder from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 1000,
    weekRate: 5000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-smallhd-dop-monitor",
    slug: "smallhd-dop-monitor",
    sku: "OUTTA-CAC-0907",
    name: "SmallHD DOP Monitor",
    brandSlug: "smallhd",
    categorySlug: "camera-accessories",
    tags: ["camera-accessories"],
    shortDescription: "Real OUTTA inventory — production monitor, available to rent.",
    description: "SmallHD DOP Monitor — production monitor from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 1000,
    weekRate: 5000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-freefly-movi-pro",
    slug: "freefly-movi-pro",
    sku: "OUTTA-CAC-0908",
    name: "Freefly MoVI Pro",
    brandSlug: "freefly",
    categorySlug: "camera-accessories",
    tags: ["camera-accessories"],
    shortDescription: "Real OUTTA inventory — 3-axis motorized gimbal, available to rent.",
    description: "Freefly MoVI Pro — 3-axis motorized gimbal from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 1500,
    weekRate: 7500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-mini-jib-12ft",
    slug: "mini-jib-12ft",
    sku: "OUTTA-CAC-0909",
    name: "Mini Jib (12ft)",
    brandSlug: "outta-essentials",
    categorySlug: "camera-accessories",
    tags: ["camera-accessories"],
    shortDescription: "Real OUTTA inventory — camera jib, available to rent.",
    description: "Mini Jib (12ft) — camera jib from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 1000,
    weekRate: 5000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-retractable-jib",
    slug: "retractable-jib",
    sku: "OUTTA-CAC-0910",
    name: "Retractable Jib",
    brandSlug: "outta-essentials",
    categorySlug: "camera-accessories",
    tags: ["camera-accessories"],
    shortDescription: "Real OUTTA inventory — camera jib, available to rent.",
    description: "Retractable Jib — camera jib from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 3500,
    weekRate: 17500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-camera-cart",
    slug: "camera-cart",
    sku: "OUTTA-CAC-0911",
    name: "Camera Cart",
    brandSlug: "outta-essentials",
    categorySlug: "camera-accessories",
    tags: ["camera-accessories"],
    shortDescription: "Real OUTTA inventory — equipment cart, available to rent.",
    description: "Camera Cart — equipment cart from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 1000,
    weekRate: 5000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-tiffen-nd-filter-single",
    slug: "tiffen-nd-filter-single",
    sku: "OUTTA-FIL-1001",
    name: "Tiffen ND Filter (Single)",
    brandSlug: "tiffen",
    categorySlug: "filters",
    tags: ["filters"],
    shortDescription: "Real OUTTA inventory — neutral density filter, available to rent.",
    description: "Tiffen ND Filter (Single) — neutral density filter from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 200,
    weekRate: 1000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-tiffen-black-pro-mist",
    slug: "tiffen-black-pro-mist",
    sku: "OUTTA-FIL-1002",
    name: "Tiffen Black Pro-Mist",
    brandSlug: "tiffen",
    categorySlug: "filters",
    tags: ["filters"],
    shortDescription: "Real OUTTA inventory — diffusion filter, available to rent.",
    description: "Tiffen Black Pro-Mist — diffusion filter from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 300,
    weekRate: 1500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-tiffen-hollywood-black-magic",
    slug: "tiffen-hollywood-black-magic",
    sku: "OUTTA-FIL-1003",
    name: "Tiffen Hollywood Black Magic",
    brandSlug: "tiffen",
    categorySlug: "filters",
    tags: ["filters"],
    shortDescription: "Real OUTTA inventory — diffusion filter, available to rent.",
    description: "Tiffen Hollywood Black Magic — diffusion filter from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 300,
    weekRate: 1500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-tiffen-black-satin",
    slug: "tiffen-black-satin",
    sku: "OUTTA-FIL-1004",
    name: "Tiffen Black Satin",
    brandSlug: "tiffen",
    categorySlug: "filters",
    tags: ["filters"],
    shortDescription: "Real OUTTA inventory — diffusion filter, available to rent.",
    description: "Tiffen Black Satin — diffusion filter from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 300,
    weekRate: 1500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-circular-polarizer",
    slug: "circular-polarizer",
    sku: "OUTTA-FIL-1005",
    name: "Circular Polarizer",
    brandSlug: "tiffen",
    categorySlug: "filters",
    tags: ["filters"],
    shortDescription: "Real OUTTA inventory — polarizing filter, available to rent.",
    description: "Circular Polarizer — polarizing filter from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 300,
    weekRate: 1500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-rota-polarizer",
    slug: "rota-polarizer",
    sku: "OUTTA-FIL-1006",
    name: "Rota Polarizer",
    brandSlug: "tiffen",
    categorySlug: "filters",
    tags: ["filters"],
    shortDescription: "Real OUTTA inventory — rotating polarizing filter, available to rent.",
    description: "Rota Polarizer — rotating polarizing filter from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 300,
    weekRate: 1500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-wooden-camera-universal-matte-box",
    slug: "wooden-camera-universal-matte-box",
    sku: "OUTTA-MTB-1101",
    name: "Wooden Camera Universal Matte Box",
    brandSlug: "wooden-camera",
    categorySlug: "matte-boxes",
    tags: ["matte-boxes"],
    shortDescription: "Real OUTTA inventory — matte box, available to rent.",
    description: "Wooden Camera Universal Matte Box — matte box from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 500,
    weekRate: 2500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-tilta-mirage-matte-box-w-vnd",
    slug: "tilta-mirage-matte-box-w-vnd",
    sku: "OUTTA-MTB-1102",
    name: "Tilta Mirage Matte Box w/ VND",
    brandSlug: "tilta",
    categorySlug: "matte-boxes",
    tags: ["matte-boxes"],
    shortDescription: "Real OUTTA inventory — matte box with built-in variable ND, available to rent.",
    description: "Tilta Mirage Matte Box w/ VND — matte box with built-in variable ND from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 400,
    weekRate: 2000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-tilta-3-way-matte-box",
    slug: "tilta-3-way-matte-box",
    sku: "OUTTA-MTB-1103",
    name: "Tilta 3-Way Matte Box",
    brandSlug: "tilta",
    categorySlug: "matte-boxes",
    tags: ["matte-boxes"],
    shortDescription: "Real OUTTA inventory — matte box, available to rent.",
    description: "Tilta 3-Way Matte Box — matte box from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 300,
    weekRate: 1500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-tilta-mini-matte-box",
    slug: "tilta-mini-matte-box",
    sku: "OUTTA-MTB-1104",
    name: "Tilta Mini Matte Box",
    brandSlug: "tilta",
    categorySlug: "matte-boxes",
    tags: ["matte-boxes"],
    shortDescription: "Real OUTTA inventory — compact matte box, available to rent.",
    description: "Tilta Mini Matte Box — compact matte box from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 150,
    weekRate: 750,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-arri-4k-hmi-m40",
    slug: "arri-4k-hmi-m40",
    sku: "OUTTA-LGT-0305",
    name: "ARRI 4K HMI M40",
    brandSlug: "arri",
    categorySlug: "lighting",
    tags: ["lighting"],
    shortDescription: "Real OUTTA inventory — HMI fixture, available to rent.",
    description: "ARRI 4K HMI M40 — HMI fixture from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 3000,
    weekRate: 15000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-nanlux-evoke-2400b",
    slug: "nanlux-evoke-2400b",
    sku: "OUTTA-LGT-0306",
    name: "Nanlux Evoke 2400B",
    brandSlug: "nanlux",
    categorySlug: "lighting",
    tags: ["lighting"],
    shortDescription: "Real OUTTA inventory — high-output LED fixture, available to rent.",
    description: "Nanlux Evoke 2400B — high-output LED fixture from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 1500,
    weekRate: 7500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-aputure-ls-1200x",
    slug: "aputure-ls-1200x",
    sku: "OUTTA-LGT-0307",
    name: "Aputure LS 1200X",
    brandSlug: "aputure",
    categorySlug: "lighting",
    tags: ["lighting"],
    shortDescription: "Real OUTTA inventory — bi-color LED fixture, available to rent.",
    description: "Aputure LS 1200X — bi-color LED fixture from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 1000,
    weekRate: 5000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-aputure-ls-1000c",
    slug: "aputure-ls-1000c",
    sku: "OUTTA-LGT-0308",
    name: "Aputure LS 1000C",
    brandSlug: "aputure",
    categorySlug: "lighting",
    tags: ["lighting"],
    shortDescription: "Real OUTTA inventory — RGBWW LED fixture, available to rent.",
    description: "Aputure LS 1000C — RGBWW LED fixture from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 1000,
    weekRate: 5000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-aputure-ls-1200d",
    slug: "aputure-ls-1200d",
    sku: "OUTTA-LGT-0309",
    name: "Aputure LS 1200D",
    brandSlug: "aputure",
    categorySlug: "lighting",
    tags: ["lighting"],
    shortDescription: "Real OUTTA inventory — daylight LED fixture, available to rent.",
    description: "Aputure LS 1200D — daylight LED fixture from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 800,
    weekRate: 4000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-aputure-ls-600c",
    slug: "aputure-ls-600c",
    sku: "OUTTA-LGT-0310",
    name: "Aputure LS 600C",
    brandSlug: "aputure",
    categorySlug: "lighting",
    tags: ["lighting"],
    shortDescription: "Real OUTTA inventory — RGBWW LED fixture, available to rent.",
    description: "Aputure LS 600C — RGBWW LED fixture from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 600,
    weekRate: 3000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-aputure-ls-300d-ii",
    slug: "aputure-ls-300d-ii",
    sku: "OUTTA-LGT-0311",
    name: "Aputure LS 300d II",
    brandSlug: "aputure",
    categorySlug: "lighting",
    tags: ["lighting"],
    shortDescription: "Real OUTTA inventory — daylight LED fixture, available to rent.",
    description: "Aputure LS 300d II — daylight LED fixture from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 300,
    weekRate: 1500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-aputure-ls-120d-ii",
    slug: "aputure-ls-120d-ii",
    sku: "OUTTA-LGT-0312",
    name: "Aputure LS 120d II",
    brandSlug: "aputure",
    categorySlug: "lighting",
    tags: ["lighting"],
    shortDescription: "Real OUTTA inventory — daylight LED fixture, available to rent.",
    description: "Aputure LS 120d II — daylight LED fixture from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 200,
    weekRate: 1000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-aputure-nova-p300c",
    slug: "aputure-nova-p300c",
    sku: "OUTTA-LGT-0313",
    name: "Aputure Nova P300c",
    brandSlug: "aputure",
    categorySlug: "lighting",
    tags: ["lighting"],
    shortDescription: "Real OUTTA inventory — RGBWW soft panel, available to rent.",
    description: "Aputure Nova P300c — RGBWW soft panel from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 600,
    weekRate: 3000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-aputure-mc-ls-mini",
    slug: "aputure-mc-ls-mini",
    sku: "OUTTA-LGT-0314",
    name: "Aputure MC (LS Mini)",
    brandSlug: "aputure",
    categorySlug: "lighting",
    tags: ["lighting"],
    shortDescription: "Real OUTTA inventory — pocket-size RGBWW light, available to rent.",
    description: "Aputure MC (LS Mini) — pocket-size RGBWW light from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 150,
    weekRate: 750,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-amaran-f22c",
    slug: "amaran-f22c",
    sku: "OUTTA-LGT-0315",
    name: "Amaran F22c",
    brandSlug: "amaran",
    categorySlug: "lighting",
    tags: ["lighting"],
    shortDescription: "Real OUTTA inventory — RGBWW soft panel, available to rent.",
    description: "Amaran F22c — RGBWW soft panel from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 600,
    weekRate: 3000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-amaran-300c",
    slug: "amaran-300c",
    sku: "OUTTA-LGT-0316",
    name: "Amaran 300c",
    brandSlug: "amaran",
    categorySlug: "lighting",
    tags: ["lighting"],
    shortDescription: "Real OUTTA inventory — RGBWW LED fixture, available to rent.",
    description: "Amaran 300c — RGBWW LED fixture from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 300,
    weekRate: 1500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-amaran-150c",
    slug: "amaran-150c",
    sku: "OUTTA-LGT-0317",
    name: "Amaran 150c",
    brandSlug: "amaran",
    categorySlug: "lighting",
    tags: ["lighting"],
    shortDescription: "Real OUTTA inventory — RGBWW LED fixture, available to rent.",
    description: "Amaran 150c — RGBWW LED fixture from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 200,
    weekRate: 1000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-godox-knowled-mat-light-4x4",
    slug: "godox-knowled-mat-light-4x4",
    sku: "OUTTA-LGT-0318",
    name: "Godox KNOWLED Mat Light 4x4",
    brandSlug: "godox",
    categorySlug: "lighting",
    tags: ["lighting"],
    shortDescription: "Real OUTTA inventory — flexible LED mat light, available to rent.",
    description: "Godox KNOWLED Mat Light 4x4 — flexible LED mat light from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 600,
    weekRate: 3000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-godox-mat-light-4x2",
    slug: "godox-mat-light-4x2",
    sku: "OUTTA-LGT-0319",
    name: "Godox Mat Light 4x2",
    brandSlug: "godox",
    categorySlug: "lighting",
    tags: ["lighting"],
    shortDescription: "Real OUTTA inventory — flexible LED mat light, available to rent.",
    description: "Godox Mat Light 4x2 — flexible LED mat light from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 500,
    weekRate: 2500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-godox-mat-light-2x2",
    slug: "godox-mat-light-2x2",
    sku: "OUTTA-LGT-0320",
    name: "Godox Mat Light 2x2",
    brandSlug: "godox",
    categorySlug: "lighting",
    tags: ["lighting"],
    shortDescription: "Real OUTTA inventory — flexible LED mat light, available to rent.",
    description: "Godox Mat Light 2x2 — flexible LED mat light from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 400,
    weekRate: 2000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-godox-airtube-light",
    slug: "godox-airtube-light",
    sku: "OUTTA-LGT-0321",
    name: "Godox Airtube Light",
    brandSlug: "godox",
    categorySlug: "lighting",
    tags: ["lighting"],
    shortDescription: "Real OUTTA inventory — flexible tube light, available to rent.",
    description: "Godox Airtube Light — flexible tube light from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 400,
    weekRate: 2000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-infinibar-full-set",
    slug: "infinibar-full-set",
    sku: "OUTTA-LGT-0322",
    name: "Infinibar Full Set",
    brandSlug: "infinibar",
    categorySlug: "lighting",
    tags: ["lighting"],
    shortDescription: "Real OUTTA inventory — LED bar light set, available to rent.",
    description: "Infinibar Full Set — LED bar light set from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 2000,
    weekRate: 10000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-nanlite-pavotube-4ft",
    slug: "nanlite-pavotube-4ft",
    sku: "OUTTA-LGT-0323",
    name: "Nanlite PavoTube 4ft",
    brandSlug: "nanlite",
    categorySlug: "lighting",
    tags: ["lighting"],
    shortDescription: "Real OUTTA inventory — RGBWW tube light, available to rent.",
    description: "Nanlite PavoTube 4ft — RGBWW tube light from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 150,
    weekRate: 750,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-nanlite-pavotube-1ft",
    slug: "nanlite-pavotube-1ft",
    sku: "OUTTA-LGT-0324",
    name: "Nanlite PavoTube 1ft",
    brandSlug: "nanlite",
    categorySlug: "lighting",
    tags: ["lighting"],
    shortDescription: "Real OUTTA inventory — RGBWW tube light, available to rent.",
    description: "Nanlite PavoTube 1ft — RGBWW tube light from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 50,
    weekRate: 250,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-12x12ft-butterfly",
    slug: "12x12ft-butterfly",
    sku: "OUTTA-LGM-1201",
    name: "12x12ft Butterfly",
    brandSlug: "outta-essentials",
    categorySlug: "lighting-modifiers",
    tags: ["lighting-modifiers"],
    shortDescription: "Real OUTTA inventory — butterfly frame, available to rent.",
    description: "12x12ft Butterfly — butterfly frame from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 800,
    weekRate: 4000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-12x12ft-checkerboard",
    slug: "12x12ft-checkerboard",
    sku: "OUTTA-LGM-1202",
    name: "12x12ft Checkerboard",
    brandSlug: "outta-essentials",
    categorySlug: "lighting-modifiers",
    tags: ["lighting-modifiers"],
    shortDescription: "Real OUTTA inventory — checkerboard net, available to rent.",
    description: "12x12ft Checkerboard — checkerboard net from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 800,
    weekRate: 4000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-12x12ft-ultrabounce",
    slug: "12x12ft-ultrabounce",
    sku: "OUTTA-LGM-1203",
    name: "12x12ft Ultrabounce",
    brandSlug: "outta-essentials",
    categorySlug: "lighting-modifiers",
    tags: ["lighting-modifiers"],
    shortDescription: "Real OUTTA inventory — ultrabounce silk, available to rent.",
    description: "12x12ft Ultrabounce — ultrabounce silk from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 800,
    weekRate: 4000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-8x8ft-checkerboard",
    slug: "8x8ft-checkerboard",
    sku: "OUTTA-LGM-1204",
    name: "8x8ft Checkerboard",
    brandSlug: "outta-essentials",
    categorySlug: "lighting-modifiers",
    tags: ["lighting-modifiers"],
    shortDescription: "Real OUTTA inventory — checkerboard net, available to rent.",
    description: "8x8ft Checkerboard — checkerboard net from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 400,
    weekRate: 2000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-8x8ft-butterfly",
    slug: "8x8ft-butterfly",
    sku: "OUTTA-LGM-1205",
    name: "8x8ft Butterfly",
    brandSlug: "outta-essentials",
    categorySlug: "lighting-modifiers",
    tags: ["lighting-modifiers"],
    shortDescription: "Real OUTTA inventory — butterfly frame, available to rent.",
    description: "8x8ft Butterfly — butterfly frame from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 400,
    weekRate: 2000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-8x8ft-ultrabounce",
    slug: "8x8ft-ultrabounce",
    sku: "OUTTA-LGM-1206",
    name: "8x8ft Ultrabounce",
    brandSlug: "outta-essentials",
    categorySlug: "lighting-modifiers",
    tags: ["lighting-modifiers"],
    shortDescription: "Real OUTTA inventory — ultrabounce silk, available to rent.",
    description: "8x8ft Ultrabounce — ultrabounce silk from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 400,
    weekRate: 2000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-8x8ft-black-out",
    slug: "8x8ft-black-out",
    sku: "OUTTA-LGM-1207",
    name: "8x8ft Black Out",
    brandSlug: "outta-essentials",
    categorySlug: "lighting-modifiers",
    tags: ["lighting-modifiers"],
    shortDescription: "Real OUTTA inventory — blackout silk, available to rent.",
    description: "8x8ft Black Out — blackout silk from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 400,
    weekRate: 2000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-6x6ft-ultrabounce",
    slug: "6x6ft-ultrabounce",
    sku: "OUTTA-LGM-1208",
    name: "6x6ft Ultrabounce",
    brandSlug: "outta-essentials",
    categorySlug: "lighting-modifiers",
    tags: ["lighting-modifiers"],
    shortDescription: "Real OUTTA inventory — ultrabounce silk, available to rent.",
    description: "6x6ft Ultrabounce — ultrabounce silk from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 300,
    weekRate: 1500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-6x6ft-checkerboard",
    slug: "6x6ft-checkerboard",
    sku: "OUTTA-LGM-1209",
    name: "6x6ft Checkerboard",
    brandSlug: "outta-essentials",
    categorySlug: "lighting-modifiers",
    tags: ["lighting-modifiers"],
    shortDescription: "Real OUTTA inventory — checkerboard net, available to rent.",
    description: "6x6ft Checkerboard — checkerboard net from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 300,
    weekRate: 1500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-4x4ft-checkerboard",
    slug: "4x4ft-checkerboard",
    sku: "OUTTA-LGM-1210",
    name: "4x4ft Checkerboard",
    brandSlug: "outta-essentials",
    categorySlug: "lighting-modifiers",
    tags: ["lighting-modifiers"],
    shortDescription: "Real OUTTA inventory — checkerboard net, available to rent.",
    description: "4x4ft Checkerboard — checkerboard net from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 200,
    weekRate: 1000,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-flags-set",
    slug: "flags-set",
    sku: "OUTTA-LGM-1211",
    name: "Flags Set",
    brandSlug: "outta-essentials",
    categorySlug: "lighting-modifiers",
    tags: ["lighting-modifiers"],
    shortDescription: "Real OUTTA inventory — flag set, available to rent.",
    description: "Flags Set — flag set from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 100,
    weekRate: 500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-floppy",
    slug: "floppy",
    sku: "OUTTA-LGM-1212",
    name: "Floppy",
    brandSlug: "outta-essentials",
    categorySlug: "lighting-modifiers",
    tags: ["lighting-modifiers"],
    shortDescription: "Real OUTTA inventory — floppy flag, available to rent.",
    description: "Floppy — floppy flag from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 150,
    weekRate: 750,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-american-stand",
    slug: "american-stand",
    sku: "OUTTA-LGM-1213",
    name: "American Stand",
    brandSlug: "outta-essentials",
    categorySlug: "lighting-modifiers",
    tags: ["lighting-modifiers"],
    shortDescription: "Real OUTTA inventory — grip stand, available to rent.",
    description: "American Stand — grip stand from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 300,
    weekRate: 1500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-haze-machine",
    slug: "haze-machine",
    sku: "OUTTA-LGM-1214",
    name: "Haze Machine",
    brandSlug: "outta-essentials",
    categorySlug: "lighting-modifiers",
    tags: ["lighting-modifiers"],
    shortDescription: "Real OUTTA inventory — atmosphere machine, available to rent.",
    description: "Haze Machine — atmosphere machine from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 300,
    weekRate: 1500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
  {
    id: "prod-smoke-machine",
    slug: "smoke-machine",
    sku: "OUTTA-LGM-1215",
    name: "Smoke Machine",
    brandSlug: "outta-essentials",
    categorySlug: "lighting-modifiers",
    tags: ["lighting-modifiers"],
    shortDescription: "Real OUTTA inventory — atmosphere machine, available to rent.",
    description: "Smoke Machine — atmosphere machine from OUTTA's real rental inventory. Pricing and availability confirmed directly by OUTTA.",
    dayRate: 300,
    weekRate: 1500,
    currency: "GHS",
    availability: "available",
    specifications: [],
    included: [],
    accessorySlugs: [],
    compatibleSlugs: [],
  },
];
