import type { ProductionPackage } from "./types";

/**
 * Preset production packages — a starting point, not a fixed order. Each
 * maps one product per role; the package builder lets a customer adjust
 * quantities or drop a role entirely before adding it to their kit.
 *
 * Every productSlug here resolves to real OUTTA inventory. Roles that had
 * no real equivalent yet (audio, batteries, media) were dropped rather than
 * kept pointing at removed demo products.
 *
 * Documentary and Commercial are tiered (OUTTA quotes them that way, at a
 * flat rate below the sum of their line items — see `PackageTier.price`).
 * Every other package has one unnamed tier and keeps the old behavior: no
 * flat price, so the site computes it live from each item's day rate.
 */
export const packages: ProductionPackage[] = [
  {
    slug: "commercial",
    name: "Commercial",
    description: "Fast-turnaround kits built for brand and agency shoots.",
    tiers: [
      {
        slug: "lite",
        label: "LITE",
        price: 2160,
        currency: "GHS",
        items: [
          { role: "Camera", productSlug: "sony-fx3", quantity: 1 },
          { role: "Support", productSlug: "manfrotto-546gb", quantity: 1 },
          { role: "Monitoring", productSlug: "cage-directors-monitor-hollyland", quantity: 1 },
          { role: "Support", productSlug: "dji-rs3-pro-with-ring", quantity: 1 },
          { role: "Lighting", productSlug: "amaran-300c", quantity: 1 },
          { role: "Lighting", productSlug: "amaran-200x-s", quantity: 1 },
          { role: "Lighting", productSlug: "nanlite-pavotube-4ft", quantity: 2 },
        ],
      },
      {
        slug: "top-boy-mid",
        label: "TOP BOY · MID",
        price: 6280,
        currency: "GHS",
        items: [
          { role: "Camera", productSlug: "sony-fx6", quantity: 1 },
          { role: "Lens", productSlug: "dzofilm-pictor-zoom-20-55mm-t2-8", quantity: 1 },
          { role: "Lens", productSlug: "dzofilm-pictor-zoom-50-125mm-t2-8", quantity: 1 },
          { role: "Accessories", productSlug: "wireless-focus-system", quantity: 1 },
          { role: "Accessories", productSlug: "tilta-3-way-matte-box", quantity: 1 },
          { role: "Accessories", productSlug: "tiffen-black-pro-mist", quantity: 1 },
          { role: "Monitoring", productSlug: "pyro-7-s-transmitter", quantity: 1 },
          { role: "Support", productSlug: "manfrotto-116-mrk3", quantity: 1 },
          { role: "Lighting", productSlug: "aputure-600x", orProductSlug: "godox-knowled-mat-light-4x4", quantity: 1 },
          { role: "Lighting", productSlug: "nanlite-fc-720b", quantity: 1 },
          { role: "Lighting", productSlug: "aputure-ls-1200d", quantity: 1 },
          { role: "Accessories", productSlug: "extension-cable", quantity: 1 },
          { role: "Accessories", productSlug: "8x8ft-diffusion", quantity: 1 },
          { role: "Accessories", productSlug: "6x6ft-checkerboard", quantity: 1 },
          { role: "Accessories", productSlug: "reflector", quantity: 1 },
        ],
      },
      {
        slug: "yolo",
        label: "YOLO",
        price: 12000,
        currency: "GHS",
        items: [
          { role: "Camera", productSlug: "arri-alexa-mini", quantity: 1 },
          { role: "Lens", productSlug: "dzofilm-vespid-prime-set-16-125mm", quantity: 1 },
          { role: "Accessories", productSlug: "wireless-focus-system", quantity: 1 },
          { role: "Accessories", productSlug: "teradek-wireless-video-transmitter", quantity: 1 },
          { role: "Monitoring", productSlug: "smallhd-dir-monitor", quantity: 1 },
          { role: "Monitoring", productSlug: "atomos-sumo-19-monitor", quantity: 1 },
          { role: "Accessories", productSlug: "tilta-3-way-matte-box", quantity: 1 },
          { role: "Accessories", productSlug: "tiffen-black-pro-mist", quantity: 1 },
          { role: "Support", productSlug: "manfrotto-116-mrk3", quantity: 1 },
          { role: "Support", productSlug: "dana-dolly-slider", quantity: 1 },
          { role: "Lighting", productSlug: "aputure-600x", quantity: 1 },
          { role: "Lighting", productSlug: "nanlite-fc-720b", quantity: 1 },
          { role: "Lighting", productSlug: "aputure-ls-1200d", quantity: 1 },
          { role: "Lighting", productSlug: "godox-knowled-mat-light-4x4", quantity: 1 },
          { role: "Accessories", productSlug: "extension-cable", quantity: 1 },
          { role: "Accessories", productSlug: "reflector", quantity: 1 },
          { role: "Accessories", productSlug: "8x8ft-diffusion", quantity: 1 },
          { role: "Accessories", productSlug: "6x6ft-checkerboard", quantity: 1 },
        ],
      },
    ],
  },
  {
    slug: "documentary",
    name: "Documentary",
    description: "Lightweight, run-and-gun setups for long shooting days.",
    tiers: [
      {
        slug: "lite",
        label: "LITE",
        price: 2360,
        currency: "GHS",
        items: [
          { role: "Camera", productSlug: "sony-fx3", quantity: 1 },
          { role: "Support", productSlug: "manfrotto-546gb", quantity: 1 },
          { role: "Accessories", productSlug: "tilta-mirage-matte-box-w-vnd", quantity: 1 },
          { role: "Support", productSlug: "dji-rs3-pro-combo-with-ring", quantity: 1 },
          { role: "Lighting", productSlug: "amaran-200x-s", quantity: 1 },
          { role: "Lighting", productSlug: "amaran-300c", quantity: 1 },
          { role: "Lighting", productSlug: "nanlite-pavotube-4ft", quantity: 1 },
          { role: "Lighting", productSlug: "nanlite-pavotube-1ft", quantity: 1 },
          { role: "Audio", productSlug: "dji-mic", quantity: 1 },
          { role: "Audio", productSlug: "zoom-recorder", quantity: 1 },
          { role: "Accessories", productSlug: "reflector", quantity: 1 },
        ],
      },
      {
        slug: "top-guy",
        label: "TOP GUY",
        price: 4320,
        currency: "GHS",
        items: [
          { role: "Camera", productSlug: "sony-fx6", quantity: 1 },
          { role: "Support", productSlug: "manfrotto-546gb", quantity: 1 },
          { role: "Support", productSlug: "dji-rs3-pro-combo-with-ring", quantity: 1 },
          { role: "Monitoring", productSlug: "wireless-directors-monitor", quantity: 1 },
          { role: "Lighting", productSlug: "amaran-300c", quantity: 1 },
          { role: "Lighting", productSlug: "aputure-600d", quantity: 1 },
          { role: "Lighting", productSlug: "nanlite-fc-720b", quantity: 1 },
          { role: "Lighting", productSlug: "nanlite-pavotube-4ft", quantity: 1 },
          { role: "Lighting", productSlug: "nanlite-pavotube-1ft", quantity: 1 },
          { role: "Accessories", productSlug: "extension-cable", quantity: 1 },
          { role: "Audio", productSlug: "zoom-recorder", quantity: 1 },
          { role: "Audio", productSlug: "sennheiser-lapel-mic", quantity: 1 },
          { role: "Accessories", productSlug: "reflector", quantity: 1 },
          { role: "Accessories", productSlug: "8x8ft-diffusion", quantity: 1 },
          { role: "Accessories", productSlug: "floppy", quantity: 1 },
        ],
      },
      {
        slug: "yolo",
        label: "YOLO",
        price: 10200,
        currency: "GHS",
        items: [
          { role: "Camera", productSlug: "sony-fx6", quantity: 1 },
          { role: "Lens", productSlug: "dzofilm-vespid-prime-set-16-125mm", quantity: 1 },
          { role: "Accessories", productSlug: "wireless-focus-system", quantity: 1 },
          { role: "Accessories", productSlug: "teradek-wireless-video-transmitter", quantity: 1 },
          { role: "Monitoring", productSlug: "smallhd-dir-monitor", quantity: 1 },
          { role: "Monitoring", productSlug: "atomos-sumo-19-monitor", quantity: 1 },
          { role: "Accessories", productSlug: "tilta-3-way-matte-box", quantity: 1 },
          { role: "Accessories", productSlug: "tiffen-black-pro-mist", quantity: 1 },
          { role: "Support", productSlug: "manfrotto-116-mrk3", quantity: 1 },
          { role: "Support", productSlug: "dana-dolly-slider", quantity: 1 },
          { role: "Lighting", productSlug: "aputure-600x", quantity: 1 },
          { role: "Lighting", productSlug: "nanlite-fc-720b", quantity: 1 },
          { role: "Lighting", productSlug: "aputure-ls-1200d", quantity: 1 },
          { role: "Lighting", productSlug: "godox-knowled-mat-light-4x4", quantity: 1 },
          { role: "Accessories", productSlug: "extension-cable", quantity: 1 },
          { role: "Accessories", productSlug: "reflector", quantity: 1 },
          { role: "Accessories", productSlug: "8x8ft-diffusion", quantity: 1 },
          { role: "Accessories", productSlug: "6x6ft-checkerboard", quantity: 1 },
        ],
      },
    ],
  },
  {
    slug: "music-video",
    name: "Music Video",
    description: "Bold lighting and specialty glass for high-concept looks.",
    tiers: [
      {
        slug: "lite",
        label: "LITE",
        price: 2520,
        currency: "GHS",
        items: [
          { role: "Camera", productSlug: "sony-fx3", quantity: 1 },
          { role: "Support", productSlug: "manfrotto-546gb", quantity: 1 },
          { role: "Accessories", productSlug: "tilta-mirage-matte-box-w-vnd", quantity: 1 },
          { role: "Support", productSlug: "dji-rs3-pro-combo-with-ring", quantity: 1 },
          { role: "Lighting", productSlug: "amaran-200x-s", quantity: 1 },
          { role: "Lighting", productSlug: "amaran-150c", quantity: 1 },
          { role: "Lighting", productSlug: "amaran-300c", quantity: 1 },
          { role: "Lighting", productSlug: "nanlite-pavotube-4ft", quantity: 1 },
          { role: "Lighting", productSlug: "nanlite-pavotube-1ft", quantity: 1 },
          { role: "Accessories", productSlug: "6x6ft-checkerboard", quantity: 1 },
          { role: "Accessories", productSlug: "reflector", quantity: 1 },
        ],
      },
      {
        slug: "top-guy",
        label: "TOP GUY",
        price: 9480,
        currency: "GHS",
        items: [
          { role: "Camera", productSlug: "arri-alexa-mini", quantity: 1 },
          { role: "Lens", productSlug: "dzofilm-pictor-zoom-20-55mm-t2-8", quantity: 1 },
          { role: "Lens", productSlug: "dzofilm-pictor-zoom-50-125mm-t2-8", quantity: 1 },
          { role: "Accessories", productSlug: "lidar-focus-pro", quantity: 1 },
          { role: "Monitoring", productSlug: "wireless-directors-monitor", quantity: 1 },
          { role: "Support", productSlug: "manfrotto-116-mrk3", quantity: 1 },
          { role: "Support", productSlug: "freefly-movi-pro", quantity: 1 },
          { role: "Lighting", productSlug: "aputure-600x", quantity: 1 },
          { role: "Lighting", productSlug: "nanlite-fc-720b", quantity: 1 },
          { role: "Lighting", productSlug: "aputure-ls-1200d", quantity: 1 },
          { role: "Lighting", productSlug: "godox-knowled-mat-light-4x4", quantity: 1 },
          { role: "Accessories", productSlug: "extension-cable", quantity: 1 },
          { role: "Accessories", productSlug: "reflector", quantity: 1 },
          { role: "Accessories", productSlug: "8x8ft-diffusion", quantity: 1 },
          { role: "Accessories", productSlug: "6x6ft-checkerboard", quantity: 1 },
        ],
      },
      {
        slug: "yolo",
        label: "YOLO",
        price: 10840,
        currency: "GHS",
        items: [
          { role: "Camera", productSlug: "arri-alexa-mini", quantity: 1 },
          { role: "Lens", productSlug: "dzofilm-vespid-prime-set-16-125mm", quantity: 1 },
          { role: "Accessories", productSlug: "wireless-focus-system", quantity: 1 },
          { role: "Accessories", productSlug: "teradek-wireless-video-transmitter", quantity: 1 },
          { role: "Monitoring", productSlug: "smallhd-dir-monitor", quantity: 1 },
          { role: "Accessories", productSlug: "tilta-3-way-matte-box", quantity: 1 },
          { role: "Accessories", productSlug: "tiffen-black-pro-mist", quantity: 1 },
          { role: "Support", productSlug: "manfrotto-116-mrk3", quantity: 1 },
          { role: "Lighting", productSlug: "aputure-600x", quantity: 1 },
          { role: "Lighting", productSlug: "nanlite-fc-720b", quantity: 1 },
          { role: "Lighting", productSlug: "aputure-ls-1200d", quantity: 1 },
          { role: "Lighting", productSlug: "godox-knowled-mat-light-4x4", quantity: 1 },
          { role: "Accessories", productSlug: "extension-cable", quantity: 1 },
          { role: "Accessories", productSlug: "reflector", quantity: 1 },
          { role: "Accessories", productSlug: "8x8ft-diffusion", quantity: 1 },
          { role: "Accessories", productSlug: "6x6ft-checkerboard", quantity: 1 },
        ],
      },
    ],
  },
  {
    slug: "short-film",
    name: "Short Film",
    description: "Compact narrative kits with room to move fast on a small crew.",
    tiers: [
      {
        slug: "lite",
        label: "LITE",
        price: 3880,
        currency: "GHS",
        items: [
          { role: "Camera", productSlug: "blackmagic-6k-pro", quantity: 1 },
          { role: "Lens", productSlug: "dzofilm-pictor-zoom-20-55mm-t2-8", quantity: 1 },
          { role: "Support", productSlug: "manfrotto-546gb", quantity: 1 },
          { role: "Monitoring", productSlug: "wireless-directors-monitor", quantity: 1 },
          { role: "Support", productSlug: "ez-fx-slider", quantity: 1 },
          { role: "Lighting", productSlug: "godox-mat-light-2x2", quantity: 1 },
          { role: "Lighting", productSlug: "nanlite-fc-720b", quantity: 1 },
          { role: "Lighting", productSlug: "amaran-200x-s", quantity: 1 },
          { role: "Accessories", productSlug: "extension-cable", quantity: 1 },
          { role: "Accessories", productSlug: "reflector", quantity: 1 },
          { role: "Accessories", productSlug: "8x8ft-diffusion", quantity: 1 },
          { role: "Accessories", productSlug: "6x6ft-checkerboard", quantity: 1 },
        ],
      },
      {
        slug: "top-guy",
        label: "TOP GUY",
        price: 9080,
        currency: "GHS",
        items: [
          { role: "Camera", productSlug: "arri-alexa-mini", quantity: 1 },
          { role: "Lens", productSlug: "dzofilm-pictor-zoom-20-55mm-t2-8", quantity: 1 },
          { role: "Lens", productSlug: "dzofilm-pictor-zoom-50-125mm-t2-8", quantity: 1 },
          { role: "Accessories", productSlug: "lidar-focus-pro", quantity: 1 },
          { role: "Monitoring", productSlug: "wireless-directors-monitor", quantity: 1 },
          { role: "Support", productSlug: "manfrotto-116-mrk3", quantity: 1 },
          { role: "Support", productSlug: "dana-dolly-slider", quantity: 1 },
          { role: "Lighting", productSlug: "aputure-600x", quantity: 1 },
          { role: "Lighting", productSlug: "nanlite-fc-720b", quantity: 1 },
          { role: "Lighting", productSlug: "aputure-ls-1200d", quantity: 1 },
          { role: "Lighting", productSlug: "godox-knowled-mat-light-4x4", quantity: 1 },
          { role: "Accessories", productSlug: "extension-cable", quantity: 1 },
          { role: "Accessories", productSlug: "reflector", quantity: 1 },
          { role: "Accessories", productSlug: "8x8ft-diffusion", quantity: 1 },
          { role: "Accessories", productSlug: "6x6ft-checkerboard", quantity: 1 },
        ],
      },
    ],
  },
  {
    slug: "wedding",
    name: "Wedding",
    description: "Discreet, reliable gear for once-only moments.",
    tiers: [
      {
        slug: "standard",
        label: "Standard",
        items: [
          { role: "Camera", productSlug: "sony-fx3", quantity: 1 },
          { role: "Lens", productSlug: "dzofilm-pictor-zoom-50-125mm-t2-8", quantity: 1 },
        ],
      },
    ],
  },
  {
    slug: "feature-film",
    name: "Feature Film",
    description: "Full production packages built around your shot list.",
    tiers: [
      {
        slug: "standard",
        label: "Standard",
        items: [
          { role: "Camera", productSlug: "arri-alexa-mini", quantity: 1 },
          { role: "Lens", productSlug: "dzofilm-vespid-prime-set-16-125mm", quantity: 1 },
          { role: "Lighting", productSlug: "aputure-600d", quantity: 2 },
          { role: "Monitoring", productSlug: "atomos-sumo-19-monitor", quantity: 1 },
          { role: "Support", productSlug: "heavy-duty-tripod", quantity: 1 },
        ],
      },
    ],
  },
  {
    slug: "interview",
    name: "Interview",
    description: "Clean two-camera setups with matched lighting.",
    tiers: [
      {
        slug: "standard",
        label: "Standard",
        items: [
          { role: "Camera", productSlug: "blackmagic-6k", quantity: 2 },
          { role: "Lens", productSlug: "canon-24-105mm", quantity: 1 },
          { role: "Lighting", productSlug: "amaran-200x-s", quantity: 2 },
          { role: "Monitoring", productSlug: "smallhd-dir-monitor", quantity: 1 },
          { role: "Support", productSlug: "heavy-duty-tripod", quantity: 2 },
        ],
      },
    ],
  },
  {
    slug: "content",
    name: "Content",
    description: "Fast, flexible kits for creators and social teams.",
    tiers: [
      {
        slug: "standard",
        label: "Standard",
        items: [
          { role: "Camera", productSlug: "sony-fx3", quantity: 1 },
          { role: "Lens", productSlug: "canon-24-105mm", quantity: 1 },
          { role: "Lighting", productSlug: "amaran-200x-s", quantity: 1 },
          { role: "Support", productSlug: "freefly-movi-pro", quantity: 1 },
        ],
      },
    ],
  },
  {
    slug: "live-production",
    name: "Live Production",
    description: "Multi-camera and audio kits built for live events.",
    tiers: [
      {
        slug: "standard",
        label: "Standard",
        items: [
          { role: "Camera", productSlug: "blackmagic-6k-pro", quantity: 2 },
          { role: "Lighting", productSlug: "godox-knowled-mat-light-4x4", quantity: 2 },
          { role: "Monitoring", productSlug: "smallhd-dop-monitor", quantity: 1 },
          { role: "Support", productSlug: "heavy-duty-tripod", quantity: 2 },
        ],
      },
    ],
  },
];
